name: yamlicious
description: >
  A library for writing yaml files
version: 0.0.1+2
author: Anders Holmgren <andersmholmgren@gmail.com>
homepage: https://github.com/Andersmholmgren/yamlicious
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  quiver: '^0.21.3'
dev_dependencies:
  unittest: any
  yaml: any
