author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for writing yaml files"
homepage: "https://github.com/Andersmholmgren/yamlicious"
name: "yamlicious"
version: "0.0.5"

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
  yaml: ^3.1.0