author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for writing yaml files"
homepage: "https://github.com/Andersmholmgren/yamlicious"
name: "yamlicious"
version: "0.1.0"
dependencies: 
  quiver: "^2.0.0+1"
dev_dependencies: 
  test: "^1.3.3"
  yaml: "^2.1.15"
environment: 
  sdk: ">=2.0.0 <3.0.0"
