author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A library for writing yaml files"
homepage: "https://github.com/Andersmholmgren/yamlicious"
name: "yamlicious"
version: "0.1.0"
dependencies: 
  quiver: ">=1.0.0"
dev_dependencies: 
  test: ">=0.12.7"
  yaml: ">=2.1.8"
environment: 
  sdk: ">=2.0.0 <3.0.0"
